import type { Metadata } from 'next'
import { fonts } from '../assets/static-fonts/fonts'
import '../assets/styles/globals.scss'

export const metadata: Metadata = {
	title: 'Луч',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={fonts.className}>
				<main>{children}</main>
			</body>
		</html>
	)
}
